### PR TITLE
Add fix in format name from https://github.com/barneyman/somagic or https://github.com/kerpz/smi2021

### PR DESCRIPTION
**Pull request by mastervolkov**

### CODE REVIEW

**Comment by Manouchehri** [comment]
Hold on, I'll just merge all your commits in. One second.

**Comment by Manouchehri** [comment]
Your repo is taking awhile to fetch... Not sure if it's my connection or if there's a lot of trash I'm pulling. Can you run ```git gc --aggressive``` and push it back up?

**Comment by mastervolkov** [comment]
Yes, i run git gc --aggressive

**Comment by Manouchehri** [comment]
Hmm, looks like my internet connection is a bit shaky. I'm getting around 5 KB/s, this might take awhile.

**Comment by Manouchehri** [comment]
Can you check my staging branch and see if I've included all of your changes?

https://github.com/Manouchehri/smi2021/commits/staging

**Comment by Manouchehri** [comment]
The commit has been merged in, along with you other changes.

**Comment by mastervolkov** [comment]
Yes, all patch applyed to staging branch well.
Thank you very much

**Comment by Manouchehri** [comment]
Let me know if you ever have any other features to include, I'll be sure to look them over and merge them.

**Comment by mastervolkov** [comment]
OK, thanks
10 апр. 2015 г. 7:41 пользователь "David Manouchehri" <
notifications@github.com> написал:
>
> Let me know if you ever have any other features to include, I'll be sure
to look them over and merge them.

**Pull request closed without merging**
